joints: ['head_pan_joint', 'head_tilt_joint']

head_pan_joint:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: head_pan_joint
    joint_speed: 2.0
    motor:
        id: 31
        init: 2048 
        min: 1600 
        max: 2500 

head_tilt_joint:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: head_tilt_joint
    joint_speed: 2.0
    motor:
        id: 32
        init: 2048 
        min: 1600 
        max: 2100 
